# Generated by Django 5.1.11 on 2025-08-11 11:35

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=4, unique=True)),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
            options={
                'db_table': 't_currency',
            },
        ),
        migrations.CreateModel(
            name='Escrow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='jobs.contract')),
            ],
            options={
                'db_table': 't_escrow',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('PENDING', 'PENDING'), ('PAYPAL', 'PAYPAL'), ('IYZICO', 'IYZICO'), ('CREDIT CARD', 'CREDIT CARD'), ('BANK TRANSFER', 'BANK TRANSFER')], max_length=13)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.contract')),
                ('currency', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='payments.currency')),
            ],
            options={
                'db_table': 't_payment',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('MEMBERSHIP FEE', 'MEMBERSHIP FEE'), ('SERVICE FEE', 'SERVICE FEE'), ('WITHDRAWAL FEE', 'WITHDRAWAL FEE'), ('WITHDRAWAL', 'WITHDRAWAL'), ('REFUND', 'REFUND')], default='SERVICE FEE', max_length=24)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('description', models.TextField()),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
            options={
                'db_table': 't_transaction',
            },
        ),
        migrations.CreateModel(
            name='UserPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_method', models.CharField(choices=[('PENDING', 'PENDING'), ('PAYPAL', 'PAYPAL'), ('IYZICO', 'IYZICO'), ('CREDIT CARD', 'CREDIT CARD'), ('BANK TRANSFER', 'BANK TRANSFER')], default='IYZICO', max_length=13)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_user_payment_method',
            },
        ),
        migrations.CreateModel(
            name='Withdrawal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=9, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('payment_method', models.CharField(choices=[('PENDING', 'PENDING'), ('PAYPAL', 'PAYPAL'), ('IYZICO', 'IYZICO'), ('CREDIT CARD', 'CREDIT CARD'), ('BANK TRANSFER', 'BANK TRANSFER')], max_length=13)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('completed_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('COMPLETED', 'COMPLETED'), ('REFUNDED', 'REFUNDED'), ('FAILED', 'FAILED')], default='PENDING', max_length=10)),
                ('payment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payments.payment')),
            ],
            options={
                'db_table': 't_withdrawal',
            },
        ),
    ]
