# Generated by Django 5.1.11 on 2025-08-11 11:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('address', '0001_initial'),
        ('core', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('FREELANCER', 'FREELANCER'), ('CLIENT', 'CLIENT')], default='FREELANCER', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('spent', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_client',
            },
        ),
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_type', models.CharField(choices=[('FREELANCER', 'FREELANCER'), ('CLIENT', 'CLIENT')], default='FREELANCER', max_length=10)),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('visibility', models.CharField(choices=[('PUBLIC', 'Public'), ('PLATFORM ONLY', 'Platform Only'), ('PRIVATE', 'Private')], default='PLATFORM ONLY', max_length=13)),
                ('badge', models.CharField(choices=[('NONE', 'NONE'), ('RISING STAR', 'RISING STAR'), ('TALENTED', 'TALENTED'), ('EXPERT', 'EXPERT'), ('MASTER', 'MASTER'), ('ELITE', 'ELITE')], default='NONE', max_length=11)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=10, max_digits=6)),
                ('title', models.CharField(blank=True, default='', max_length=64, null=True)),
                ('bio', models.TextField(blank=True, default='', null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('balance', models.DecimalField(decimal_places=2, default=0, max_digits=18)),
                ('total_points', models.PositiveSmallIntegerField(default=50)),
                ('hoursperweek', models.PositiveSmallIntegerField(default=40)),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='address.address')),
                ('skills', models.ManyToManyField(to='core.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 't_professional',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
            ],
            options={
                'db_table': 't_portfolio',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('job_title', models.CharField(max_length=64)),
                ('company_name', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
            ],
            options={
                'db_table': 't_experience',
            },
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('area_of_study', models.CharField(max_length=64)),
                ('degree', models.CharField(max_length=64)),
                ('school_name', models.CharField(max_length=64)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
            ],
            options={
                'db_table': 't_education',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acquired_date', models.DateField()),
                ('name', models.CharField(max_length=64)),
                ('authority', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
            ],
            options={
                'db_table': 't_certification',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
            ],
            options={
                'db_table': 't_availability',
            },
        ),
    ]
