# Generated by Django 5.1.11 on 2025-08-11 11:35

import django.core.validators
import django.db.models.deletion
import django.db.models.manager
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_user_first_name_user_last_name_client_professional_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('slug', models.SlugField(max_length=256, unique_for_date='created_date')),
                ('status', models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('CHANGE REQUEST', 'CHANGE REQUEST'), ('DONE', 'DONE')], default='TODO', max_length=14)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField()),
                ('min_budget', models.DecimalField(decimal_places=0, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)])),
                ('max_budget', models.DecimalField(decimal_places=0, default=10, max_digits=9, validators=[django.core.validators.MinValueValidator(10)])),
                ('is_active', models.BooleanField(default=True)),
                ('is_public', models.BooleanField(default=True)),
                ('job_type', models.CharField(choices=[('FIXED', 'FIXED'), ('HOURLY', 'HOURLY')], default='FIXED', max_length=6)),
                ('required_points', models.PositiveSmallIntegerField(default=4)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.client')),
                ('skills', models.ManyToManyField(to='core.skill')),
            ],
            options={
                'db_table': 't_job',
                'ordering': ['-created_date'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Professional proposal amount to complete the job', max_digits=18)),
                ('commission', models.DecimalField(decimal_places=2, help_text='Commission Percentage Rate. Ex; 10', max_digits=5, validators=[django.core.validators.MaxValueValidator(100)])),
                ('service_fee', models.DecimalField(decimal_places=2, help_text='Platform Service Fee', max_digits=18)),
                ('total_result', models.DecimalField(decimal_places=2, help_text='Total Professional Money', max_digits=18)),
                ('coverletter', models.TextField()),
                ('is_accepted', models.BooleanField(default=False)),
                ('viewed_date', models.DateTimeField(blank=True, help_text='View date when a client view the proposal we need to set this field', null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.professional')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 't_proposal',
                'unique_together': {('created_by', 'job')},
            },
        ),
        migrations.CreateModel(
            name='FlaggedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, null=True, validators=[django.core.validators.MaxLengthValidator(280)], verbose_name='Reason')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_flagged_jobs', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
            ],
            options={
                'db_table': 't_flagged_job',
                'unique_together': {('job', 'reported_by')},
            },
        ),
        migrations.CreateModel(
            name='ProfessionalSavedJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('saved_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='professional_saved_jobs', to='users.professional')),
            ],
            options={
                'db_table': 't_professional_saved_job',
                'unique_together': {('job', 'saved_by')},
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('updated_date', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('PENDING', 'PENDING'), ('OPEN', 'OPEN'), ('CLOSED', 'CLOSED')], default='PENDING', max_length=7)),
                ('workstatus', models.CharField(choices=[('TODO', 'TODO'), ('IN PROGRESS', 'IN PROGRESS'), ('IN REVIEW', 'IN REVIEW'), ('CHANGE REQUEST', 'CHANGE REQUEST'), ('DONE', 'DONE')], default='TODO', max_length=14)),
                ('hours_worked', models.PositiveSmallIntegerField(default=1)),
                ('close_reason', models.TextField(blank=True, null=True)),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.job')),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jobs.proposal')),
            ],
            options={
                'db_table': 't_contract',
                'unique_together': {('job', 'proposal')},
            },
            managers=[
                ('obs', django.db.models.manager.Manager()),
            ],
        ),
    ]
